### ISSUE TITLE
pairing issue

### ISSUE THREAD

**Issue by botts7** [kind3r/hass-addons#12]
```
Error while initialising lock Error: Failed setting lock time
    at TTLock.calibrateTimeCommand (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:174:23)
    at async TTLock.initLock (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:143:13)
    at async Manager.initLock (/app/src/manager.js:167:19)
    at async WebSocket.<anonymous> (/app/api/index.js:52:30)
```

lock adds administrator then deletes administrator

**Comment by botts7** [comment]
also can get 

Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at Function.aesDecrypt (/app/node_modules/ttlock-sdk-js/dist/util/AESUtil.js:46:58)
    at CommandEnvelope.getData (/app/node_modules/ttlock-sdk-js/dist/api/CommandEnvelope.js:169:42)
    at CommandEnvelope.generateCommand (/app/node_modules/ttlock-sdk-js/dist/api/CommandEnvelope.js:237:74)
    at CommandEnvelope.getCommand (/app/node_modules/ttlock-sdk-js/dist/api/CommandEnvelope.js:149:14)
    at TTLock.getAESKeyCommand (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:100:40)
    at async TTLock.initLock (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:135:28)
    at async Manager.initLock (/app/src/manager.js:167:19)
    at async WebSocket.<anonymous> (/app/api/index.js:52:30) {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_EVP_BAD_DECRYPT'
}
Error while initialising lock Error: Decryption failed
    at Function.aesDecrypt (/app/node_modules/ttlock-sdk-js/dist/util/AESUtil.js:51:19)
    at CommandEnvelope.getData (/app/node_modules/ttlock-sdk-js/dist/api/CommandEnvelope.js:169:42)
    at CommandEnvelope.generateCommand (/app/node_modules/ttlock-sdk-js/dist/api/CommandEnvelope.js:237:74)
    at CommandEnvelope.getCommand (/app/node_modules/ttlock-sdk-js/dist/api/CommandEnvelope.js:149:14)
    at TTLock.getAESKeyCommand (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:100:40)
    at async TTLock.initLock (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:135:28)
    at async Manager.initLock (/app/src/manager.js:167:19)
    at async WebSocket.<anonymous> (/app/api/index.js:52:30)

**Comment by botts7** [comment]
also addon log has 

> ttlock-hass-integration@0.2.1 start /app
> node ./index.js

[Error: ENOENT: no such file or directory, access '/data/lockData.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/data/lockData.json'
}
[Error: ENOENT: no such file or directory, access '/data/aliasData.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/data/aliasData.json'

**Comment by kind3r** [comment]
Let's keep the discussion within one issue #11
