### ISSUE TITLE
Lock cannot communicate with my Raspberry Pi 4 when door is closed

### ISSUE THREAD

**Issue by dibyadip-das** [kind3r/hass-addons#22]
The door lock cannot communicate with my Raspberry Pi 4 when the door is closed.
Does this seem to be a connectivity problem? Although RSSI remains at -64dB

<img src="https://user-images.githubusercontent.com/47345141/125571438-6001d1e3-7867-4072-930b-5e516a99e1fa.png" alt="drawing" width="400"/>

Here are the logs:
```
Monitor started
noble: unknown peripheral undefined RSSI update!
noble warning: unknown handle 11 disconnected!
Monitor stopped
noble: unknown peripheral undefined RSSI update!
noble warning: unknown handle 11 disconnected!
noble: unknown peripheral undefined RSSI update!
noble warning: unknown handle 11 disconnected!
Peripheral connect start
Peripheral connect triggered
Peripheral connect error: Error: connection canceled!
    at Peripheral.cancelConnect (/app/node_modules/@abandonware/noble/lib/peripheral.js:61:26)
    at NobleDevice.connect (/app/node_modules/ttlock-sdk-js/dist/scanner/noble/NobleDevice.js:91:37)
    at async TTBluetoothDevice.connect (/app/node_modules/ttlock-sdk-js/dist/device/TTBluetoothDevice.js:47:17)
    at async TTLock.connect (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:53:27)
    at async Manager._connectLock (/app/src/manager.js:583:21)
    at async Manager.unlockLock (/app/src/manager.js:187:13)
Connect failed
Lock connect failed
Connect to lock failed F7:7A:64:56:2E:82
Peripheral connect triggered
Peripheral connect start
Peripheral connect triggered
Peripheral connect error: Error: connection canceled!
    at Peripheral.cancelConnect (/app/node_modules/@abandonware/noble/lib/peripheral.js:61:26)
    at NobleDevice.connect (/app/node_modules/ttlock-sdk-js/dist/scanner/noble/NobleDevice.js:91:37)
    at async TTBluetoothDevice.connect (/app/node_modules/ttlock-sdk-js/dist/device/TTBluetoothDevice.js:47:17)
    at async TTLock.connect (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:53:27)
    at async Manager._connectLock (/app/src/manager.js:583:21)
    at async Manager.unlockLock (/app/src/manager.js:187:13)
    at async WebSocket.<anonymous> (/app/api/index.js:78:30)
Connect failed
Lock connect failed
Connect to lock failed F7:7A:64:56:2E:82
Peripheral connect triggered
noble: unknown peripheral undefined RSSI update!
noble warning: unknown handle 11 disconnected!
noble: unknown peripheral undefined RSSI update!
```
I am aware of the esp32 gateway option but at the current time, the instructions are too complex for me to execute. I will try out all the alternatives

**Comment by Fusseldieb** [comment]
Just because the RSSI is decent, doesn't mean the signal reliability is good too.

Those locks seem very picky about the data they receive and their radio in general isn't that good either.

Also, be noted that the antenna on the Pi 4 just isn't that good **either**, for example. See: https://www.raspberrypi.org/forums/viewtopic.php?t=260594

**Comment by dibyadip-das** [comment]
Thanks for the suggestion. Yes, I already ordered one from TP-link and will post the results here as soon as I get up and running.

**Comment by dibyadip-das** [comment]
In case I restart the Addon. Do we lose pairing with the lock? I just did it and the lock seems to be no more paired?

**Comment by dibyadip-das** [comment]
As suggested by @Fusseldieb I was able to get a better connection using an external bluetooth dongle strategically located somewhere away from the interface of the PI using an usb extension cable.

**Comment by Fusseldieb** [comment]
Nice to know that this was in fact the problem! 

Thank you for the issue report and I hope you the best :)
