### ISSUE TITLE
Able To Lock/Unlock and recognize lock but no other functions seem to work

### ISSUE THREAD

**Issue by DanielGPina** [kind3r/hass-addons#25]
I got the Lock to pair, but I cant seem to unpair it, or do any "admin" functions on the lock and the lock timer changed for -1 for some reason.

> Connected to known lock, reading general data
========= check admin
Lock waiting for connection to be completed
macro_adminLogin: Error: Failed checkAdmin response
at TTLock.checkAdminCommand (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:551:23)
at async TTLock.macro_adminLogin (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:1329:32)
at async TTLock.onConnected (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:1239:111)
========= lockSound
Failed reading all general data from lock Error: Failed to set audio mode
at TTLock.audioManageCommand (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:234:23)
at async TTLock.onConnected (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:1252:38)
Connected to paired lock D3:D9:13:9B:FF:06
========= check admin
========= check admin
macro_adminLogin: Error: Command already in progress
at TTBluetoothDevice.sendCommand (/app/node_modules/ttlock-sdk-js/dist/device/TTBluetoothDevice.js:146:19)
at TTLock.checkAdminCommand (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:546:52)
at TTLock.macro_adminLogin (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:1329:43)
at TTLock.resetLock (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:474:28)
at Manager.resetLock (/app/src/manager.js:560:32)
at async WebSocket. (/app/api/index.js:254:27)
macro_adminLogin: Error: Failed checkAdmin response
at TTLock.checkAdminCommand (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:551:23)
at async TTLock.macro_adminLogin (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:1329:32)
at async TTLock.getAutolockTime (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:371:29)
at async Function.fromTTLock (/app/api/Lock.js:49:27)
at async Function.sendLockStatus (/app/api/WsApi.js:43:21)
========= lockSound
Error getting lock sound status Error: Failed to set audio mode
at TTLock.audioManageCommand (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:234:23)
at async TTLock.getLockSound (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:428:38)
at async Function.fromTTLock (/app/api/Lock.js:51:22)
at async Function.sendLockStatus (/app/api/WsApi.js:43:21)

**Comment by DanielGPina** [comment]
On the cylinder locks apparently you have to factory reset the lock so the commands go through, maybe because I already had it paired with the TTLOCK app before. You just need to open and factory reset, (2 star screws with center pins). The lock seemed compliant after!
