### ISSUE TITLE
can't pair a lock

### ISSUE THREAD

**Issue by ajctrl** [kind3r/hass-addons#39]
Debug communication ON
> ttlock-hass-integration@0.2.1 start
> node ./index.js
MQTT connected
Monitor started
Server started
Monitor stopped
BLE Scan started
Discovered new lock: {"id":"debcaa1245ba","manufacturer":"unknown","model":"unknown","hardware":"unknown","firmware":"unknown","address":"DE:BC:AA:12:45:BA","rssi":-63,"protocolType":5,"protocolVersion":3,"scene":2,"groupId":0,"orgId":0,"lockType":5,"isTouch":true,"isUnlock":false,"hasEvents":false,"isSettingMode":true,"txPowerLevel":0,"batteryCapacity":100,"date":0,"isWristband":false,"isRoomLock":true,"isSafeLock":false,"isBicycleLock":false,"isLockcar":false,"isGlassLock":false,"isPadLock":false,"isCyLinder":false,"isRemoteControlDevice":false,"isDfuMode":false,"isNoLockService":false,"remoteUnlockSwitch":0,"disconnectStatus":0,"parkStatus":0,"lockSound":-1,"autoLockTime":-1,"privateData":{},"operationLog":[]}
New lock found, stopping scan
BLE Scan stopped
Refreshing paired locks
Monitor started
Monitor stopped
Peripheral connect start
Peripheral connect triggered
Peripheral connect error: Error: connection canceled!
    at Peripheral.cancelConnect (/app/node_modules/@abandonware/noble/lib/peripheral.js:61:26)
    at NobleDevice.connect (/app/node_modules/ttlock-sdk-js/dist/scanner/noble/NobleDevice.js:91:37)
    at async TTBluetoothDevice.connect (/app/node_modules/ttlock-sdk-js/dist/device/TTBluetoothDevice.js:47:17)
    at async TTLock.connect (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:53:27)
    at async Manager._connectLock (/app/src/manager.js:583:21)
    at async Manager.initLock (/app/src/manager.js:163:13)
    at async WebSocket.<anonymous> (/app/api/index.js:52:30)
Connect failed
Lock connect failed
Connect to lock failed DE:BC:AA:12:45:BA
Connect allready in progress
Connect to lock failed DE:BC:AA:12:45:BA

I'm at a loss.

**Comment by ajctrl** [comment]
macro_adminLogin: Error: Failed checkRandom response
    at TTLock.checkRandomCommand (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:580:23)
    at async TTLock.macro_adminLogin (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:1333:17)
    at async TTLock.onConnected (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:1239:111)

macro_adminLogin: Error: Disconnected while waiting for response
    at TTBluetoothDevice.sendCommand (/app/node_modules/ttlock-sdk-js/dist/device/TTBluetoothDevice.js:193:39)
    at async TTLock.checkRandomCommand (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:575:34)
    at async TTLock.macro_adminLogin (/app/node_modules/ttlock-sdk-js/dist/device/TTLockApi.js:1333:17)
    at async TTLock.getAutolockTime (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:371:29)
    at async Function.fromTTLock (/app/api/Lock.js:49:27)
    at async Function.sendLockStatus (/app/api/WsApi.js:43:21)


Connected to paired lock DE:BC:AA:12:45:BA
Successful connect attempt to paired lock DE:BC:AA:12:45:BA
Disconnected from lock DE:BC:AA:12:45:BA
Connect allready in progress
Connect to lock failed DE:BC:AA:12:45:BA
Connect allready in progress
Connect to lock failed DE:BC:AA:12:45:BA

once disconnected, it'll be dead til you restart the addon and try again.
