### ISSUE TITLE
Not able to Pair

### ISSUE THREAD

**Issue by mabrochu-helpox** [kind3r/hass-addons#40]
I bought a hornbill door lock on amazon. I configured the lock in ttlock successfully. Then I reset the lock to factory settings. I see the lock in the addon but i was not able to complete the pairing.

> ttlock-hass-integration@0.2.1 start
> node ./index.js
[Error: ENOENT: no such file or directory, access '/data/lockData.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/data/lockData.json'
}
[Error: ENOENT: no such file or directory, access '/data/aliasData.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/data/aliasData.json'
}
MQTT connected
Monitor started
Server started
Monitor stopped
BLE Scan started
Discovered new lock: {"id":"d052b39be306","manufacturer":"unknown","model":"unknown","hardware":"unknown","firmware":"unknown","address":"D0:52:B3:9B:E3:06","rssi":-59,"protocolType":5,"protocolVersion":3,"scene":2,"groupId":0,"orgId":0,"lockType":5,"isTouch":true,"isUnlock":false,"hasEvents":false,"isSettingMode":true,"txPowerLevel":0,"batteryCapacity":100,"date":0,"isWristband":false,"isRoomLock":true,"isSafeLock":false,"isBicycleLock":false,"isLockcar":false,"isGlassLock":false,"isPadLock":false,"isCyLinder":false,"isRemoteControlDevice":false,"isDfuMode":false,"isNoLockService":false,"remoteUnlockSwitch":0,"disconnectStatus":0,"parkStatus":0,"lockSound":-1,"autoLockTime":-1,"privateData":{},"operationLog":[]}
New lock found, stopping scan
BLE Scan stopped
Refreshing paired locks
Monitor started
Monitor stopped
Peripheral connect start
Peripheral connect triggered
Peripheral connect error: Error: Unknown Connection Identifier (0x2)
    at NobleBindings.onLeConnComplete (/app/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:240:13)
    at Hci.emit (events.js:400:28)
    at Hci.processLeConnComplete (/app/node_modules/@abandonware/noble/lib/hci-socket/hci.js:795:8)
    at Hci.processLeMetaEvent (/app/node_modules/@abandonware/noble/lib/hci-socket/hci.js:766:10)
    at Hci.onSocketData (/app/node_modules/@abandonware/noble/lib/hci-socket/hci.js:596:12)
    at BluetoothHciSocket.emit (events.js:400:28)
Connect failed
Lock connect failed
Connect to lock failed D0:52:B3:9B:E3:06

**Comment by mabrochu-helpox** [comment]
Was able to pair but still have error
