### ISSUE TITLE
Pairing Issue

### ISSUE THREAD

**Issue by Daryn-L** [kind3r/hass-addons#43]
Just wondered if there are any ideas for getting it to pair?

RPI 4b

Log:

`> ttlock-hass-integration@0.2.1 start
> node ./index.js
[Error: ENOENT: no such file or directory, access '/data/lockData.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/data/lockData.json'
}
[Error: ENOENT: no such file or directory, access '/data/aliasData.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/data/aliasData.json'
}
MQTT connected
Monitor started
Server started
Discovered new lock: {"id":"74d3207f21cf","manufacturer":"unknown","model":"unknown","hardware":"unknown","firmware":"unknown","address":"74:D3:20:7F:21:CF","rssi":-66,"protocolType":5,"protocolVersion":3,"scene":2,"groupId":0,"orgId":0,"lockType":5,"isTouch":true,"isUnlock":false,"hasEvents":false,"isSettingMode":true,"txPowerLevel":0,"batteryCapacity":100,"date":0,"isWristband":false,"isRoomLock":true,"isSafeLock":false,"isBicycleLock":false,"isLockcar":false,"isGlassLock":false,"isPadLock":false,"isCyLinder":false,"isRemoteControlDevice":false,"isDfuMode":false,"isNoLockService":false,"remoteUnlockSwitch":0,"disconnectStatus":0,"parkStatus":0,"lockSound":-1,"autoLockTime":-1,"privateData":{},"operationLog":[]}
Monitor stopped
Peripheral connect start
Peripheral connect triggered
Peripheral connect error: Error: connection canceled!
    at Peripheral.cancelConnect (/app/node_modules/@abandonware/noble/lib/peripheral.js:61:26)
    at NobleDevice.connect (/app/node_modules/ttlock-sdk-js/dist/scanner/noble/NobleDevice.js:91:37)
    at async TTBluetoothDevice.connect (/app/node_modules/ttlock-sdk-js/dist/device/TTBluetoothDevice.js:47:17)
    at async TTLock.connect (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:53:27)
    at async Manager._connectLock (/app/src/manager.js:583:21)
    at async Manager.initLock (/app/src/manager.js:163:13)
    at async WebSocket.<anonymous> (/app/api/index.js:52:30)
Connect failed
Lock connect failed
Connect to lock failed 74:D3:20:7F:21:CF`

**Comment by badmuz** [comment]
I got same issue here

**Comment by racksync-v0** [comment]
same here

**Comment by justinlawrence** [comment]
I had it working, but did not get any information or events when
doors were opened and closed, so finally gave up and went back to the
TTLock app. I think I would have persisted if I had been able to issue
temporary codes, like I could to with the native TTLock app. I will have a
look again if any big progress is made.

**Comment by mousawm** [comment]
Same problem here.

` > ttlock-hass-integration@0.2.1 start
> node ./index.js
[Error: ENOENT: no such file or directory, access '/data/lockData.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/data/lockData.json'
}
[Error: ENOENT: no such file or directory, access '/data/aliasData.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/data/aliasData.json'
}
MQTT connected
Monitor started
Server started
Monitor stopped
BLE Scan started
BLE Scan stopped
Refreshing paired locks
Monitor started
Discovered new lock: {"id":"17803e848d20","manufacturer":"unknown","model":"unknown","hardware":"unknown","firmware":"unknown","address":"17:80:3E:84:8D:20","rssi":-80,"protocolType":5,"protocolVersion":3,"scene":2,"groupId":0,"orgId":0,"lockType":5,"isTouch":true,"isUnlock":false,"hasEvents":false,"isSettingMode":true,"txPowerLevel":0,"batteryCapacity":17,"date":0,"isWristband":false,"isRoomLock":true,"isSafeLock":false,"isBicycleLock":false,"isLockcar":false,"isGlassLock":false,"isPadLock":false,"isCyLinder":false,"isRemoteControlDevice":false,"isDfuMode":false,"isNoLockService":false,"remoteUnlockSwitch":0,"disconnectStatus":0,"parkStatus":0,"lockSound":-1,"autoLockTime":-1,"privateData":{},"operationLog":[]}
Monitor stopped
BLE Scan started
BLE Scan stopped
Refreshing paired locks
Monitor started
Monitor stopped
Peripheral connect start
Peripheral connect triggered
Peripheral connect error: Error: connection canceled!
    at Peripheral.cancelConnect (/app/node_modules/@abandonware/noble/lib/peripheral.js:61:26)
    at NobleDevice.connect (/app/node_modules/ttlock-sdk-js/dist/scanner/noble/NobleDevice.js:91:37)
    at async TTBluetoothDevice.connect (/app/node_modules/ttlock-sdk-js/dist/device/TTBluetoothDevice.js:47:17)
    at async TTLock.connect (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:53:27)
    at async Manager._connectLock (/app/src/manager.js:583:21)
    at async Manager.initLock (/app/src/manager.js:163:13)
    at async WebSocket.<anonymous> (/app/api/index.js:52:30)
Connect failed
Lock connect failed
Connect to lock failed 17:80:3E:84:8D:20 `
