### ISSUE TITLE
Do i need to unpair with my phone for this to work?

### ISSUE THREAD

**Issue by stevearmitage** [kind3r/hass-addons#44]
I have setup the lock with my phone and the app. To use the HomeAssistant integration, do I need to reset the lock and disconnect from the app? It looks like my Bluetooth can see the phone, but not pair/connect

Is there a way I can maintain existing fingerprints?

Thanks!

**Comment by mikewesner** [comment]
Im just starting to play with this, but I got this far.  I had to reset the lock from the back of the lock and use TTLock only.  You can't have both paired.  You have to reset it and redo the fingerprints.

**Comment by stevearmitage** [comment]
I get the device showing, but it does not pair
<img width="378" alt="Screenshot 2022-09-01 at 11 19 34" src="https://user-images.githubusercontent.com/29444933/187824820-6536a4b3-c10c-49fe-901e-747a9f926b17.png">

I get the following in my logs
```
BLE Scan started
Emmiting paramsChanged { batteryCapacity: true, newEvents: false, lockedStatus: false }
BLE Scan stopped
Refreshing paired locks
Monitor started
Monitor stopped
Peripheral connect start
Peripheral connect triggered
Peripheral connect error: Error: connection canceled!
    at Peripheral.cancelConnect (/app/node_modules/@abandonware/noble/lib/peripheral.js:61:26)
    at NobleDevice.connect (/app/node_modules/ttlock-sdk-js/dist/scanner/noble/NobleDevice.js:91:37)
    at async TTBluetoothDevice.connect (/app/node_modules/ttlock-sdk-js/dist/device/TTBluetoothDevice.js:47:17)
    at async TTLock.connect (/app/node_modules/ttlock-sdk-js/dist/device/TTLock.js:53:27)
    at async Manager._connectLock (/app/src/manager.js:583:21)
    at async Manager.initLock (/app/src/manager.js:163:13)
    at async WebSocket.<anonymous> (/app/api/index.js:52:30)
Connect failed
Lock connect failed
Connect to lock failed 2E:39:B6:C6:EB:C6
```
